### ISSUE TITLE
我使用yarn start以后出现的错误

### ISSUE THREAD

**Issue by little233** [journey-ad/chat-room#2]
前排声明
系统是debian是用的vm虚拟机
这是yarn install的过程yarn install
yarn install v1.22.4
info No lockfile found.
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
warning sqlite3 > node-gyp > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning sqlite3 > node-gyp > request > har-validator@5.1.5: this
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 22.34s.

yarn start
yarn run v1.22.4
$ node index.js
/www/wwwroot/chat.xiaoxiang.ml/chat-room/node_modules/mongoose/lib/connection.js:581
    throw new MongooseError('The `uri` parameter to `openUri()` must be a ' +
    ^

MongooseError: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.
    at NativeConnection.Connection.openUri (/www/wwwroot/chat.xiaoxiang.ml/chat-room/node_modules/mongoose/lib/connection.js:581:11)
    at Mongoose.connect (/www/wwwroot/chat.xiaoxiang.ml/chat-room/node_modules/mongoose/lib/index.js:335:15)
    at Object.<anonymous> (/www/wwwroot/chat.xiaoxiang.ml/chat-room/db/mongodb.js:6:10)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/www/wwwroot/chat.xiaoxiang.ml/chat-room/db/index.js:9:10)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by journey-ad** [comment]
请阅读 README，数据库使用 mongoDB 需要配置连接字符串，或者使用 SQLite 无需配置

**Comment by little233** [comment]
> 请阅读README，数据库使用mongoDB需要配置连接字符串，或者使用SQLite无需配置

就不能支持mysql嘛。

**Comment by journey-ad** [comment]
你可以参照 db 目录下的现有代码自己实现一个 MySQL 的支持，API 保持一致就可以了
